from pathlib import Path

p=Path('test/detection.test.ts')
s=p.read_text(encoding='utf-8')
s=s.replace("test('연석(D6)은 4g 를 넘지만 보조 조건이 하나도 안 서서 기각 — ΔV 여유가 0.14 m/s 뿐이다'", "test('mock D6: 회전 조건은 통과해도 6g 미만이면 후보가 아니다'")
s=s.replace('assert.equal(impact!.fired, true);', 'assert.equal(impact!.fired, false);').replace('assert.equal(support!.fired, false);','assert.equal(support!.fired, true);')
s=s.replace("test('stress_100hz 에서 실험이 놓친 A3 사선 충돌은 서버도 놓친다 — 알려진 한계'", "test('mock A3: 새 초기값 300deg/s를 적용한다'")
s=s.replace("bank_deg: 0, quiet_s: 25 })).decision, 'reject');", "bank_deg: 0, quiet_s: 25 })).decision, 'alarm');")
s=s.replace("test('후보 뒤 계속 움직이면 기각 — 특이도는 충격 이후에서 나온다 (2.3)'", "test('후보 뒤 움직임으로 후보를 취소하지 않는다'")
s=s.replace("bank_deg: 0, quiet_s: 3 })).decision, 'reject');", "bank_deg: 0, quiet_s: 3 })).decision, 'alarm');")
s=s.replace("assert.equal(decision, 'alarm_unverified');", "assert.equal(decision, 'alarm');",1)
s=s.replace("test('충격은 섰는데 보조 지표가 비어 있으면 기각하지 않는다 — 무동작이면 경보, 움직이면 기각'", "test('보조 지표가 없으면 무동작과 무관하게 정보 부족'")
s=s.replace("assert.equal(decision, 'alarm_unverified');", "assert.equal(decision, 'undetermined');")
s=s.replace("judge(onlyImpact(2)).decision, 'reject'", "judge(onlyImpact(2)).decision, 'undetermined'")
s=s.replace("judge(crash!.indicators).decision, 'alarm_unverified'", "judge(crash!.indicators).decision, 'alarm'")
s=s.replace("assert.deepEqual(reports.map((r) => judge(r.indicators).traces.find((t) => t.rule === 'support')!.fired), [true, false]);", "assert.deepEqual(reports.map((r) => r.analysis.decision), ['candidate', 'no_candidate']);")
s=s.replace('// 헬멧 IMU 실험(2026-09-28) analysis/run_evaluation.csv 의 실제 실행 값.', '// Mock summary fixtures inspired by prior reports; not measured validation.')
s=s.replace("test('실험의 사고 실행은 경보, 가장 센 정상 주행은 기각'", "test('mock summary fixtures exercise the initial report thresholds'")
p.write_text(s,encoding='utf-8')

p=Path('test/incidents.test.ts');s=p.read_text(encoding='utf-8')
s=s.replace("'false_alarm'","'rider_cancelled'").replace("괜찮아요 → 오탐으로 기록되고 아무에게도 연락하지 않는다","괜찮아요 → 본인 응답으로 종료하며 실제 사고 여부는 확정하지 않는다")
s=s.replace("/김라이더님에게 사고가 감지됐고 30초 동안 응답이 없었어요\\. 현재 위치: https:\\/\\/rg\\.test\\/s\\/[\\w-]{43} 119에도 자동으로 신고해요\\./", "/강한 충격이 감지됐고 30초 동안 본인 응답을 확인하지 못했어요/")
s=s.replace("assert.equal(contacts.state, 'done');", "assert.equal(contacts.state, 'now');")
s=s.replace("assert.deepEqual(contacts.detail.notified, [{ priority: 1, name: '엄마' }]);", "assert.deepEqual(contacts.detail.notified, []);\n  assert.equal(contacts.detail.reason, 'simulated');")
s=s.replace("delivery: 'sent'", "delivery: 'simulated'").replace("detail.emergency, 'sent'", "detail.emergency, 'simulated'").replace("detail.delivery, 'sent'", "detail.delivery, 'simulated'")
s=s.replace("['detected:done', 'response:done', 'contacts:done', 'emergency:done', 'record:todo']", "['detected:done', 'response:done', 'contacts:now', 'emergency:skipped', 'record:todo']")
s=s.replace("['detected:done', 'response:done', 'contacts:done', 'emergency:done', 'order:done', 'record:todo']", "['detected:done', 'response:done', 'contacts:now', 'emergency:skipped', 'order:now', 'record:todo']")
s=s.replace("['detected:done', 'response:done', 'contacts:done', 'emergency:done', 'record:done']", "['detected:done', 'response:done', 'contacts:skipped', 'emergency:skipped', 'record:done']")
s=s.replace("assert.equal(status.order.status, 'reassigned');", "assert.equal(status.order.status, 'held');")
s=s.replace("/김라이더님에게 사고가 감지됐어요/", "/김라이더님에게 강한 충격이 감지됐어요/").replace("/119에 자동으로 신고했어요/", "/전송 시연 기록이에요/")
s=s.replace("events.includes('emergency_reported') && events.includes('order_reassigned')", "events.includes('emergency_report_simulated') && events.includes('order_reassignment_simulated')")
s=s.replace("assert.equal(t.reports.length, 2);", "assert.equal(t.reports.length, 1);")
s=s.replace("  assert.match(t.reports[1]!, /앞서 자동 신고한 김라이더 010-1234-5678 사고 건 — 라이더가 앱에서 직접 도움을 요청했어요/);", "  // A simulated report never causes a follow-up to a real service.")
s=s.replace("assert.deepEqual(sent.map((s) => s.to), ['01011111111', '01011111111']);", "assert.deepEqual(sent.map((s) => s.to), ['01011111111']);")
s=s.replace("  assert.match(sent[1]!.body, /김라이더님이 괜찮다고 응답해서 사고 대응을 마쳤어요/);", "")
s=s.replace("  assert.match(t.reports[1]!, /라이더 본인이 앱에서 '괜찮다'고 응답했어요/);", "")
s=s.replace("body: { response: 'ok' } })).status, 409);", "body: { response: 'ok' } })).status, 200);")
s=s.replace("assert.ok(contactSms(t).some((s) => s.to === '01011111111' && /119 자동 신고가 전송되지 않았어요/.test(s.body)));", "assert.equal(contactSms(t).filter((s) => /119 자동 신고가 전송되지 않았어요/.test(s.body)).length, 0, 'capture-only contacts are not real recipients of follow-ups');")
p.write_text(s,encoding='utf-8')

p=Path('test/detections-v1.test.ts');s=p.read_text(encoding='utf-8')
s=s.replace('contact_notified:demo','contact_notification_simulated:demo').replace('emergency_reported:demo','emergency_report_simulated:demo').replace('order_reassigned:demo','order_reassignment_simulated:demo')
p.write_text(s,encoding='utf-8')

p=Path('test/indicators-api.test.ts');s=p.read_text(encoding='utf-8')
s=s.replace("active.source, 'device'", "active.source, 'test'").replace(".json.incident.source, 'tag'", ".json.incident.source, 'test'")
s=s.replace("assert.ok(t.sms.some((s) => s.to === '01011111111' && s.body.includes('응답이 없었어요')));", "assert.deepEqual(t.sms, [], 'unknown provenance cannot contact real recipients');")
p.write_text(s,encoding='utf-8')
