"""계정 저장소의 Postgres 판. 규칙은 api/auth.py 와 같고 저장소만 다르다.

둘을 두는 이유는 기기와 클라우드가 서로 다른 것을 요구하기 때문이다. 파이는 LAN
안에서 인터넷 없이 돌아야 하므로 (README §1) 파일 하나로 끝나는 SQLite 가 맞다.
Postgres 로 통째로 갈아타면 인터넷이 끊긴 방에서 로그인이 막힌다 — 생체 모니터링
기기에서 그건 고장이다.

반대로 Render 무료 플랜은 재배포·재시작마다 컨테이너를 새로 만든다. 거기서는
state/users.db 가 매번 날아가서 쓸 때마다 다시 가입해야 한다.

그래서 DATABASE_URL 이 있으면 이쪽, 없으면 저쪽이다 (api/main.py). 파이는 그 값을
두지 않으므로 아무것도 바뀌지 않는다.

비밀번호 해싱·아이디 검증·모델은 api/auth.py 것을 그대로 쓴다. 두 벌로 두면 한쪽만
고치는 날이 오고, 그 순간 두 배포의 계정 규칙이 갈린다.
"""

from __future__ import annotations

import json
import secrets
import time
from datetime import UTC, datetime
from typing import Any

import structlog
from psycopg.errors import UniqueViolation
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool

from api.auth import (
    PROFILE_FIELDS,
    SESSION_SWEEP_S,
    SESSION_TTL,
    SESSION_TTL_BRIEF,
    Account,
    AuthError,
    Principal,
    Profile,
    Role,
    check_password,
    check_username,
    hash_password,
)
from core.layout import Layout

log = structlog.get_logger(__name__)

# SQLite 판과 같은 테이블이지만 타입은 Postgres 것을 쓴다. 옮겨 적을 때 달라지는 곳:
#   INTEGER PRIMARY KEY   -> IDENTITY      (rowid 별칭이 없다)
#   approved/active       -> BOOLEAN       (0/1 을 그대로 두면 화면이 다 참으로 본다)
#   created_at/expires_at -> TIMESTAMPTZ   (문자열로 두면 만료 비교가 사전순이 된다)
#   COLLATE NOCASE        -> lower() 유니크 인덱스
_SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    role          TEXT NOT NULL,
    -- 두 값을 나누는 이유는 api/auth.py 에 적혀 있다. "아직 승인 안 됨"과 "쓰다가
    -- 막힘"은 관리자가 보는 목록도, 당사자에게 할 말도 다르다.
    approved      BOOLEAN NOT NULL DEFAULT TRUE,
    active        BOOLEAN NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL
);
-- Postgres 에는 NOCASE 콜레이션이 없다. 조회도 lower() 로 해야 이 인덱스를 탄다.
CREATE UNIQUE INDEX IF NOT EXISTS users_username_ci ON users (lower(username));
CREATE TABLE IF NOT EXISTS sessions (
    token      TEXT PRIMARY KEY,
    user_id    BIGINT REFERENCES users(id) ON DELETE CASCADE,  -- NULL 이면 비회원
    expires_at TIMESTAMPTZ NOT NULL
);
-- 화면 배치. 계정마다 하나다 (core/layout.py).
CREATE TABLE IF NOT EXISTS layouts (
    user_id  BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    hero     TEXT NOT NULL,
    -- "order" 는 SQL 예약어라 이름을 바꿨다. JSON 배열이다.
    ordering TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS profiles (
    user_id        BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    display_name   TEXT NOT NULL DEFAULT '',
    birthdate      TEXT NOT NULL DEFAULT '',
    sex            TEXT NOT NULL DEFAULT '',
    phone          TEXT NOT NULL DEFAULT '',
    email          TEXT NOT NULL DEFAULT '',
    guardian_name  TEXT NOT NULL DEFAULT '',
    guardian_email TEXT NOT NULL DEFAULT '',
    notes          TEXT NOT NULL DEFAULT '',
    updated_at     TIMESTAMPTZ
);

-- Supabase 는 Data API(PostgREST)를 켜 두면 public 스키마의 테이블을 인터넷에
-- 열어 준다. 새 테이블에 anon 권한을 기본으로 주는 설정이 함께 켜져 있으면, 아래
-- 세 테이블이 그대로 노출된다. anon 키는 브라우저에 박으라고 만든 값이라 비밀이
-- 아니다 — sessions 가 읽히는 순간 토큰을 쿠키에 넣어 관리자로 들어올 수 있다.
--
-- 이 앱은 Postgres 프로토콜로 직접 붙는다. REST 쪽 권한은 한 번도 쓰지 않으므로
-- 회수한다. 콘솔에서 끄는 것으로 대신하지 않는 이유는, 프로젝트를 새로 만들 때
-- 체크 하나를 잊으면 조용히 다시 열리기 때문이다.
--
-- anon/authenticated 는 Supabase 에만 있는 역할이라 없을 수도 있다. 다른 Postgres
-- 에서 이 블록이 죽으면 앱이 통째로 안 뜬다.
DO $$
DECLARE r text;
BEGIN
    FOREACH r IN ARRAY ARRAY['anon', 'authenticated'] LOOP
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
            EXECUTE format('REVOKE ALL ON users, sessions, profiles, layouts FROM %I', r);
        END IF;
    END LOOP;
END $$;

-- 권한을 회수한 위에 한 겹 더 둔다. 정책을 하나도 안 만들었으므로 RLS 를 거치는
-- 쪽에서는 아무 줄도 안 보인다. 테이블 소유자인 이 앱은 RLS 를 우회하므로 영향이 없다.
ALTER TABLE users    ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE layouts  ENABLE ROW LEVEL SECURITY;
"""

# register() 가 "아직 아무도 없는가"를 세는 동안 다른 가입이 끼어들면 관리자가 둘
# 생긴다. SQLite 는 BEGIN IMMEDIATE 로 막았는데 Postgres 에는 그 문법이 없고, 기본
# 격리수준(Read Committed)에서는 두 트랜잭션의 COUNT 가 서로를 못 본다.
#
# 값 자체에 의미는 없다. 이 잠금을 쓰는 곳이 여기뿐이라 겹치지만 않으면 된다.
_REGISTER_LOCK = 8_474_912


class PgUsers:
    """계정 저장소. api/auth.py 의 Users 와 같은 메서드를 같은 뜻으로 낸다.

    모든 메서드는 블로킹이므로 호출하는 쪽에서 asyncio.to_thread 로 부른다 —
    SQLite 판과 같은 이유다 (1Hz 샘플 루프가 같은 이벤트 루프에서 돈다).
    """

    def __init__(self, dsn: str) -> None:
        # 요청마다 연결을 새로 열지 않는다. SQLite 는 파일 열기라 공짜였지만 여기서는
        # TLS 핸드셰이크가 붙고, 로그인 한 번에 그 비용을 서너 번 낸다.
        #
        # max_size 를 크게 잡지 않는 이유: Supabase 무료 플랜은 풀러 연결 수가
        # 빠듯하고, Render 무료는 인스턴스가 하나라 이보다 더 쓸 일이 없다.
        self.pool: ConnectionPool[Any] = ConnectionPool(
            dsn,
            min_size=1,
            max_size=3,
            kwargs={"row_factory": dict_row},
            open=False,
        )
        self._swept = 0.0  # 만료 세션을 마지막으로 치운 시각 (monotonic)

    def init(self) -> None:
        self.pool.open(wait=True)
        with self.pool.connection() as conn:
            conn.execute(_SCHEMA)
        log.info("auth_pg.ready")

    def close(self) -> None:
        self.pool.close()

    def ensure_admin(self, username: str, password: str) -> None:
        """환경변수로 정한 관리자 계정을 보장한다. 판단 근거는 api/auth.py 와 같다."""
        username = check_username(username)
        if len(password) < 8:
            raise AuthError(400, "관리자 비밀번호는 8자 이상이어야 한다")

        digest = hash_password(password)
        with self.pool.connection() as conn:
            # register() 와 같은 잠금을 잡는다. 관리자를 세우는 중에 누가 가입하면
            # 그 사람이 "첫 번째"로 세어져 관리자가 둘이 된다.
            conn.execute("SELECT pg_advisory_xact_lock(%s)", (_REGISTER_LOCK,))
            row = conn.execute(
                "SELECT id FROM users WHERE lower(username) = lower(%s)", (username,)
            ).fetchone()
            if row is None:
                conn.execute(
                    "INSERT INTO users"
                    " (username, password_hash, role, approved, active, created_at)"
                    " VALUES (%s, %s, 'admin', TRUE, TRUE, %s)",
                    (username, digest, datetime.now(UTC)),
                )
                event = "auth_pg.admin_created"
            else:
                conn.execute(
                    "UPDATE users SET password_hash = %s, role = 'admin',"
                    " approved = TRUE, active = TRUE WHERE id = %s",
                    (digest, int(row["id"])),
                )
                event = "auth_pg.admin_synced"
        log.info(event, username=username)

    # --- 가입 / 로그인 ---

    def register(self, username: str, password: str) -> Account:
        """첫 가입자는 관리자로 바로 들어오고, 그 뒤로는 승인을 기다린다.

        판단 근거는 api/auth.py 의 같은 메서드에 적혀 있다.
        """
        username = check_username(username)
        if len(password) < 8:
            raise AuthError(400, "비밀번호는 8자 이상이어야 한다")

        digest = hash_password(password)
        now = datetime.now(UTC)
        try:
            with self.pool.connection() as conn:
                # 트랜잭션이 끝나면 자동으로 풀린다. 세는 것과 넣는 것이 이 잠금
                # 안에 같이 있어야 관리자가 둘 생기지 않는다.
                conn.execute("SELECT pg_advisory_xact_lock(%s)", (_REGISTER_LOCK,))
                counted = conn.execute("SELECT COUNT(*) AS n FROM users").fetchone()
                first = int(counted["n"]) == 0 if counted else True
                role: Role = "admin" if first else "member"
                row = conn.execute(
                    "INSERT INTO users"
                    " (username, password_hash, role, approved, active, created_at)"
                    " VALUES (%s, %s, %s, %s, TRUE, %s)"
                    " RETURNING id",
                    (username, digest, role, first, now),
                ).fetchone()
        except UniqueViolation:
            # 트랜잭션 밖에서 받는다. 안에서 잡으면 psycopg 가 실패한 트랜잭션을
            # 커밋하려 들어서 진짜 이유가 다른 예외에 덮인다.
            raise AuthError(409, "이미 쓰고 있는 아이디다") from None

        assert row is not None  # RETURNING 이라 INSERT 가 성공하면 항상 한 줄이다
        log.info("auth_pg.registered", username=username, role=role, approved=first)
        return Account(
            id=int(row["id"]),
            username=username,
            role=role,
            approved=first,
            active=True,
            created_at=now,
        )

    def taken(self, username: str) -> bool:
        """이미 있는 아이디인가. 대소문자는 가리지 않는다."""
        with self.pool.connection() as conn:
            row = conn.execute(
                "SELECT 1 FROM users WHERE lower(username) = lower(%s)", (username,)
            ).fetchone()
        return row is not None

    def login(self, username: str, password: str, remember: bool = False) -> str:
        """세션 토큰. 판단 근거는 api/auth.py 의 같은 메서드에 적혀 있다."""
        with self.pool.connection() as conn:
            row = conn.execute(
                "SELECT id, password_hash, role, approved, active FROM users"
                " WHERE lower(username) = lower(%s)",
                (username.strip(),),
            ).fetchone()

            # 아이디가 없을 때도 해시를 한 번 계산한다. 안 그러면 응답 시간만 재도
            # 어떤 아이디가 존재하는지 알 수 있다.
            stored = str(row["password_hash"]) if row else hash_password(password)
            if not check_password(password, stored) or row is None:
                raise AuthError(401, "아이디 또는 비밀번호가 맞지 않다")
            if not row["approved"]:
                raise AuthError(403, "관리자 승인을 기다리는 중이다")
            if not row["active"]:
                raise AuthError(403, "차단된 계정이다")

            return self._open(conn, user_id=int(row["id"]), remember=remember)

    def login_as_guest(self) -> str:
        with self.pool.connection() as conn:
            return self._open(conn, user_id=None, remember=False)

    def _open(self, conn: Any, user_id: int | None, remember: bool) -> str:
        token = secrets.token_urlsafe(32)
        conn.execute(
            "INSERT INTO sessions (token, user_id, expires_at) VALUES (%s, %s, %s)",
            (token, user_id, datetime.now(UTC) + (SESSION_TTL if remember else SESSION_TTL_BRIEF)),
        )
        return token

    def logout(self, token: str) -> None:
        with self.pool.connection() as conn:
            conn.execute("DELETE FROM sessions WHERE token = %s", (token,))

    # --- 조회 ---

    def principal(self, token: str) -> Principal | None:
        """토큰이 가리키는 사람. 없거나 만료됐으면 None.

        만료 판정은 이 조회가 직접 한다. 청소는 가끔만 돈다 — 근거는 api/auth.py
        의 같은 메서드에 적혀 있다. 여기서는 그 왕복 한 번이 인터넷 너머다.
        """
        now = datetime.now(UTC)
        with self.pool.connection() as conn:
            row = conn.execute(
                "SELECT u.username, u.role, u.approved, u.active FROM sessions s"
                " LEFT JOIN users u ON u.id = s.user_id"
                " WHERE s.token = %s AND s.expires_at > %s",
                (token, now),
            ).fetchone()
            self._sweep(conn, now)

        if row is None:
            return None
        if row["username"] is None:
            return Principal(username=None, role="guest")
        # 차단됐거나 승인이 철회된 계정의 옛 세션이 살아 있으면 안 된다.
        if not row["active"] or not row["approved"]:
            return None
        return Principal(username=str(row["username"]), role=str(row["role"]))  # type: ignore[arg-type]

    def _sweep(self, conn: Any, now: datetime) -> None:
        """만료된 세션 줄을 치운다. 요청마다 하지 않는다 (api/auth.py 의 _sweep)."""
        clock = time.monotonic()
        if clock - self._swept < SESSION_SWEEP_S:
            return
        self._swept = clock
        conn.execute("DELETE FROM sessions WHERE expires_at <= %s", (now,))

    def accounts(self) -> list[Account]:
        with self.pool.connection() as conn:
            rows = conn.execute(
                "SELECT id, username, role, approved, active, created_at FROM users ORDER BY id"
            ).fetchall()
        return [
            Account(
                id=int(r["id"]),
                username=str(r["username"]),
                role=str(r["role"]),  # type: ignore[arg-type]
                approved=bool(r["approved"]),
                active=bool(r["active"]),
                # TIMESTAMPTZ 라 드라이버가 datetime 으로 준다. SQLite 판처럼
                # 문자열을 되파싱할 일이 없다.
                created_at=r["created_at"],
            )
            for r in rows
        ]

    # --- 프로필 ---

    def profile(self, username: str) -> Profile:
        """아직 아무것도 안 적었으면 빈 양식을 준다. 없는 값을 지어내지 않는다."""
        with self.pool.connection() as conn:
            row = conn.execute(
                "SELECT p.* FROM profiles p JOIN users u ON u.id = p.user_id"
                " WHERE lower(u.username) = lower(%s)",
                (username,),
            ).fetchone()

        if row is None:
            return Profile()
        return Profile(
            **{field: str(row[field]) for field in PROFILE_FIELDS},
            updated_at=row["updated_at"],
        )

    def save_profile(self, username: str, profile: Profile) -> Profile:
        now = datetime.now(UTC)
        columns = ", ".join(PROFILE_FIELDS)
        marks = ", ".join(["%s"] * len(PROFILE_FIELDS))
        updates = ", ".join(f"{field} = excluded.{field}" for field in PROFILE_FIELDS)

        with self.pool.connection() as conn:
            row = conn.execute(
                "SELECT id FROM users WHERE lower(username) = lower(%s)", (username,)
            ).fetchone()
            if row is None:  # pragma: no cover - 세션이 가리키는 계정이라 여기 오지 않는다
                raise AuthError(404, "그런 계정이 없다")
            conn.execute(
                f"INSERT INTO profiles (user_id, {columns}, updated_at)"
                f" VALUES (%s, {marks}, %s)"
                f" ON CONFLICT (user_id) DO UPDATE SET {updates}, updated_at = excluded.updated_at",
                (
                    int(row["id"]),
                    *(getattr(profile, field) for field in PROFILE_FIELDS),
                    now,
                ),
            )

        # 언제 적었는지는 서버 시계로 정한다. 본문에 실려 온 값은 버린다.
        return profile.model_copy(update={"updated_at": now})

    # --- 화면 배치 ---

    def layout(self, username: str) -> Layout:
        """이 계정이 마지막으로 둔 배치. 없으면 기본값이다."""
        with self.pool.connection() as conn:
            row = conn.execute(
                "SELECT l.hero, l.ordering FROM layouts l JOIN users u ON u.id = l.user_id"
                " WHERE lower(u.username) = lower(%s)",
                (username,),
            ).fetchone()

        if row is None:
            return Layout()
        try:
            return Layout(hero=str(row["hero"]), order=json.loads(str(row["ordering"])))
        except (ValueError, TypeError):
            # 배치 하나 때문에 화면이 안 뜨면 곤란하다. 못 읽으면 기본값이다.
            log.warning("auth_pg.layout_unreadable", username=username)
            return Layout()

    def save_layout(self, username: str, value: Layout) -> Layout:
        with self.pool.connection() as conn:
            row = conn.execute(
                "SELECT id FROM users WHERE lower(username) = lower(%s)", (username,)
            ).fetchone()
            if row is None:  # pragma: no cover - 세션이 가리키는 계정이라 여기 오지 않는다
                raise AuthError(404, "그런 계정이 없다")
            conn.execute(
                "INSERT INTO layouts (user_id, hero, ordering) VALUES (%s, %s, %s)"
                " ON CONFLICT (user_id) DO UPDATE SET hero = excluded.hero,"
                " ordering = excluded.ordering",
                (int(row["id"]), value.hero, json.dumps(value.order)),
            )
        return value

    def set_approved(self, user_id: int, approved: bool) -> None:
        """가입 승인을 내주거나 거둔다. 거두면 열려 있던 세션도 같이 닫는다.

        관리자에게서는 거둘 수 없다. 마지막 관리자를 잠그면 되돌릴 사람이 없다.
        """
        with self.pool.connection() as conn:
            row = conn.execute("SELECT role FROM users WHERE id = %s", (user_id,)).fetchone()
            if row is None:
                raise AuthError(404, "그런 계정이 없다")
            if row["role"] == "admin" and not approved:
                raise AuthError(400, "관리자 계정의 승인은 거둘 수 없다")
            conn.execute("UPDATE users SET approved = %s WHERE id = %s", (approved, user_id))
            if not approved:
                conn.execute("DELETE FROM sessions WHERE user_id = %s", (user_id,))
        log.info("auth_pg.set_approved", user_id=user_id, approved=approved)

    def set_active(self, user_id: int, active: bool) -> None:
        """계정을 차단하거나 되돌린다. 차단하면 열려 있던 세션도 같이 닫는다."""
        with self.pool.connection() as conn:
            row = conn.execute("SELECT role FROM users WHERE id = %s", (user_id,)).fetchone()
            if row is None:
                raise AuthError(404, "그런 계정이 없다")
            if row["role"] == "admin" and not active:
                raise AuthError(400, "관리자 계정은 차단할 수 없다")
            conn.execute("UPDATE users SET active = %s WHERE id = %s", (active, user_id))
            if not active:
                conn.execute("DELETE FROM sessions WHERE user_id = %s", (user_id,))
        log.info("auth_pg.set_active", user_id=user_id, active=active)
